language: php
php:
  - "5.4"
  - "5.3"
  - "5.2"

before_install:
  - git submodule update --init --recursive

services:
  - mysql

before_script:
  - ./tests/setup/db-mysql.sh
  - ./tests/setup/profile.sh travis
