language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
  - "5.2"

install:
  - sudo apt-get install apache2
  - sudo apt-get install libapache2-mod-php5

services:
  - mysql

before_script:
  - ./tests/setup/apache.sh
  - ./tests/setup/php-pear.sh
  - ./tests/setup/db-mysql.sh
  - ./tests/setup/profile.sh travis

script:
  - ./tests/syntax.sh
  - phpunit --colors tests

matrix:
  allow_failures:
    - php: "5.2"
