language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
  - "5.2"

services:
  - mysql

before_script:
  - ./tests/setup/php-pear.sh
  - ./tests/setup/db-mysql.sh
  - ./tests/setup/profile.sh travis

script:
  - ./tests/syntax.sh
  - phpunit --colors tests

matrix:
  allow_failures:
    - php: 5.2
